triggers:
- envs: []
  name: green_taxi_pipe_sched
  pipeline_uuid: green_taxi_etl
  schedule_interval: '@daily'
  schedule_type: time
  settings: {}
  sla: null
  start_time: 2024-02-02 13:17:00
  status: active
  variables: {}
